title: Marcus Brady
description: >
  Masters student within the chemical and physical sciences with a focus on machine learning.

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation links
header_pages:
  - README.md
  - research.md

# Social links
minima:
  skin: dark
     - { platform: linkedin,       user_url: "https://www.linkedin.com/in/marcusebrady" }
